### ISSUE TITLE
‘D_DESC’ was not declared in this scope

### ISSUE THREAD

**Issue by a-deriva** [Costor/nvmpi-obs-streamFX#1]
D_DESC definition has been removed in streamfx v0.10

**Comment by Costor** [comment]
You are right; the macro D_DESC has been removed from strings.hpp.  However this dealt with text description of options, so nothing close the the core functionality. 
However, as I said, I barely have the capacity to maintain this; I would have to upgrade everything to new versions etc which would take time.
However:
As you can see from my comments (marked with PST) in the six source files that I provided I copied the original nvenc* files and did only minor changes. 
Any chance that you may just take the new nvenc* files streamfx 0.10, copy them to nvmpi* and redo my changes in them? 
Chances are really great that this would work.

**Comment by Amhehu** [comment]
Hi Costor!
Thanks for your work!
I used your code and adopt it to the current version of streamfx. If you give me appropriate permissions I could push it in a branch.

**Comment by Costor** [comment]
Hi Amhehu!
Of course this would be great. 
I've just invited you to this repository. 
Feel free to add a branch (probably with a streamFX version number in its name?) and to update the repository description as well as this issue.

**Comment by Amhehu** [comment]
I just pushed my current version in Branch StreamFX-0.11.0
Tomorrow I will test that the shell script works on a fresh Ubuntu 20.04 installation on my Jetson.

**Comment by Amhehu** [comment]
I checked the script and it seems everything is fine.
I had just a test device which I have to give back. I hope my updated code helps anyone :)

**Comment by Costor** [comment]
Super, sure it will help.
I will rename the main branch to make your branch more prominent as it deserves.

**Comment by lblabr** [comment]
> I checked the script and it seems everything is fine. I had just a test device which I have to give back. I hope my updated code helps anyone :)

i'm trying to get it running on my jetson do i need to use special obs version 27.0.0 ... 27.2.4 ?

**Comment by Amhehu** [comment]
Sorry, I don't remember and have no device to check it.

**Comment by lblabr** [comment]
okay, any hints?

**Comment by Amhehu** [comment]
Not really, I have had the device just for about 2 weeks for tests. I would suggest I used the most current version.
Anyway I think meanwhile there are newer versions which are supported.
